server:
  port: 8082

eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: trip-service
          uri: lb://trip-service
          predicates:
            - Path=/passenger/**, /trip/**
        - id: ticket-service
          uri: lb://ticket-service
          predicates:
            - Path=/ticket/**