server:
  port: 8082

eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: NODOTRIPPASSENGER
          uri: lb://NODOTRIPPASSENGER
          predicates:
            - Path=/**
        - id: NODOTICKET
          uri: lb://NODOTICKET
          predicates:
            - Path=/**